/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        try {



            // access key value pairs from constructor in class Quote
            Quote quote = new Quote("", new App().getNumbersAPI());

            // transform the quote into json and use quoteWriter to send the quote to the json file
            FileWriter quoteWriter = new FileWriter("src/main/resources/apiquotestest.json");
            Gson gson = new Gson();
            // send quote to json file (which overwrites current quote)
            gson.toJson(quote, quoteWriter);



//            Quote[] quotes = new Quote[2];
//            quotes[0] = quote;
//            quotes[1] = quote;
//            gson.toJson(quotes, quoteWriter);

            Quote[] superCoolQuotesArray = gson.fromJson(
                    new FileReader(new File("src/main/resources/recentquotes.json")),
                    Quote[].class);
            // create new quote array + 1
            // add quote to superCoolQuotesArray + 1
            // gson.toJson superCoolQuotesArray, quotewriter



            // print out the quote to the console (which was also stored to json file)
            System.out.println(quote);

            //System.out.println(gson.toJson(new App().getNumbersAPI()));

            quoteWriter.close();


        } catch (IOException e) {
            // couldn't access the api, so get something from the json file
            readQuoteFromFile();
        }
    }

    // === JSON SUPPLIES QUOTE ===
    public static void readQuoteFromFile() throws FileNotFoundException {
        // === Put quotes from JSON into Array ===
        // read all quotes from file into superCoolQuotesArray variable
        Gson gson = new Gson();
        Quote[] superCoolQuotesArray = gson.fromJson(
                new FileReader(new File("src/main/resources/recentquotes.json")),
                Quote[].class);

        //System.out.println(superCoolQuotesArray[17]);
        System.out.println(getRandomQuote(superCoolQuotesArray));
    }


    // === API ===
    // API comes from: http://numbersapi.com/#42
    // base code to read from an api from Michelle Ferreirae
    public String getNumbersAPI() throws IOException {
        //URL jqueryUrl = new URL("http://numbersapi.com/12/12/date");
        URL jqueryUrl = new URL("http://numbersapi.com/random/year");
        HttpURLConnection connection = (HttpURLConnection) jqueryUrl.openConnection();
        // read
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder data = new StringBuilder();
        String line = reader.readLine();
        // if something is there, read line
        while(line != null) {
            data.append(line);
            line = reader.readLine();
        }
        return data.toString();
    }


    // === HELPER METHOD ===
    // get a random quote from an array of quotes using a helper method
    public static Quote getRandomQuote(Quote[] quotes) {
        // get random number
        int index = (int)(Math.random() * quotes.length);
        return quotes[index];
    }
}
